# Generated by Django 5.0.1 on 2024-02-05 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=255, unique=True)),
                ('instagram_username', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('private', models.BooleanField(default=False)),
                ('posts_count', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('follows_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
