# Generated by Django 5.0.1 on 2024-02-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fake',
            field=models.IntegerField(default=0),
        ),
    ]
